# INTERACTIVE_MODELS_PATH: "./experiments/iter_mask/cocolvis_hrnet18s/000_first-try/checkpoints/"
EXPS_PATH: "./experiments"

# datasets
CRACKS_PATH: "/kaggle/input/crack-segmentation-dataset/crack_segmentation_dataset"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
    HRNETV2_W18: "/kaggle/input/hrnetv2-w18-imagenet-pretrained/hrnetv2_w18_imagenet_pretrained.pth"
#     HRNETV2_W18_SMALL: "/home/admin/workspace/project/data/weights/hrnet_w18_small_model_v2.pth"
#     HRNETV2_W32: "/home/admin/workspace/project/data/weights/hrnetv2_w32_imagenet_pretrained.pth"
#     HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
#     HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
#     SEGFORMER_B0: "/home/admin/workspace/project/data/weights/Segformer/mit_b0.pth"
#     SEGFORMER_B1: "/home/admin/workspace/project/data/weights/Segformer/mit_b1.pth"
#     SEGFORMER_B3: "/home/admin/workspace/project/data/weights/Segformer/mit_b3.pth"
#     PPLCNET_X1 : "/home/admin/workspace/project/data/weights/PPLC/PP-LCNet/PPLCNet_x1_0_ssld_pretrained.pth"
#     MOBILENETV2: "/home/admin/workspace/project/data/weights/mobilenetV2-15498621.pth"
